name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git Credentials and Push
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "auto-bot@example.com"
          echo "Last refresh: $(date)" > keepalive.txt
          git add keepalive.txt
          git commit -m "🔄 Auto-commit to keep Streamlit alive" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
